security:
    # Para definir los roles se usa patrón ROLE_MODULO_ACCION
    # MODULO debe ser igual a la url mostrada al acceder al módulo
    # ACCION generalmente va a ser LECTURA o ESCRITURA
    # por ejemplo ROLE_OBRAS_LECTURA
    role_hierarchy:
        ROLE_ADMIN: ROLE_USER

        ROLE_ALL: [ROLE_ADMIN, ROLE_GRUPO_ALL, ROLE_USUARIO_ALL, ROLE_AUDITORIA_VIEW, ROLE_VEHICULO_ALL, ROLE_MARCA_ALL, ROLE_PROVEEDOR_ALL, ROLE_CLIENTE_ALL]

        ROLE_MENU_SEGURIDAD: [ROLE_USER, ROLE_MENU_SEGURIDAD]

        ROLE_GRUPO_VIEW: [ROLE_USER, ROLE_GRUPO_VIEW]
        ROLE_GRUPO_CREATE: [ROLE_GRUPO_VIEW, ROLE_GRUPO_CREATE]
        ROLE_GRUPO_EDIT: [ROLE_GRUPO_VIEW, ROLE_GRUPO_EDIT]
        ROLE_GRUPO_DELETE: [ROLE_GRUPO_VIEW, ROLE_GRUPO_DELETE]
        ROLE_GRUPO_RESET_PASSWORD: [ROLE_GRUPO_VIEW, ROLE_GRUPO_RESET_PASSWORD]
        ROLE_GRUPO_ALL: [ROLE_GRUPO_CREATE, ROLE_GRUPO_EDIT, ROLE_GRUPO_DELETE, ROLE_GRUPO_ALL]

        ROLE_USUARIO_VIEW: [ROLE_USER, ROLE_USUARIO_VIEW]
        ROLE_USUARIO_CREATE: [ROLE_USUARIO_VIEW, ROLE_USUARIO_CREATE]
        ROLE_USUARIO_EDIT: [ROLE_USUARIO_VIEW, ROLE_USUARIO_EDIT]
        ROLE_USUARIO_DELETE: [ROLE_USUARIO_VIEW, ROLE_USUARIO_DELETE]
        ROLE_USUARIO_HABILITAR : [ROLE_USUARIO_VIEW, ROLE_USUARIO_HABILITAR]
        ROLE_USUARIO_DESHABILITAR: [ROLE_USUARIO_VIEW, ROLE_USUARIO_DESHABILITAR]
        ROLE_USUARIO_ALL: [ROLE_USUARIO_CREATE, ROLE_USUARIO_EDIT, ROLE_USUARIO_DELETE, ROLE_USUARIO_DESHABILITAR, ROLE_USUARIO_HABILITAR, ROLE_USUARIO_ALL]
        
        ROLE_AUDITORIA_VIEW: [ROLE_USER, ROLE_AUDITORIA_VIEW]
        
        ROLE_VEHICULO_VIEW: [ROLE_VEHICULO_VIEW]
        ROLE_VEHICULO_CREATE: [ROLE_VEHICULO_VIEW, ROLE_VEHICULO_CREATE]
        ROLE_VEHICULO_EDIT: [ROLE_VEHICULO_VIEW, ROLE_VEHICULO_EDIT]
        ROLE_VEHICULO_DELETE: [ROLE_VEHICULO_VIEW, ROLE_VEHICULO_DELETE]
        ROLE_VEHICULO_ALL: [ROLE_VEHICULO_CREATE, ROLE_VEHICULO_EDIT, ROLE_VEHICULO_DELETE, ROLE_VEHICULO_ALL]

        ROLE_MARCA_VIEW: [ROLE_MARCA_VIEW]
        ROLE_MARCA_CREATE: [ROLE_MARCA_VIEW, ROLE_MARCA_CREATE]
        ROLE_MARCA_EDIT: [ROLE_MARCA_VIEW, ROLE_MARCA_EDIT]
        ROLE_MARCA_DELETE: [ROLE_MARCA_VIEW, ROLE_MARCA_DELETE]
        ROLE_MARCA_ALL: [ROLE_MARCA_CREATE, ROLE_MARCA_EDIT, ROLE_MARCA_DELETE, ROLE_MARCA_ALL]

        ROLE_PROVEEDOR_VIEW: [ROLE_PROVEEDOR_VIEW]
        ROLE_PROVEEDOR_CREATE: [ROLE_PROVEEDOR_VIEW, ROLE_PROVEEDOR_CREATE]
        ROLE_PROVEEDOR_EDIT: [ROLE_PROVEEDOR_VIEW, ROLE_PROVEEDOR_EDIT]
        ROLE_PROVEEDOR_DELETE: [ROLE_PROVEEDOR_VIEW, ROLE_PROVEEDOR_DELETE]
        ROLE_PROVEEDOR_ALL: [ROLE_PROVEEDOR_CREATE, ROLE_PROVEEDOR_EDIT, ROLE_PROVEEDOR_DELETE, ROLE_PROVEEDOR_ALL]

        ROLE_CLIENTE_VIEW: [ROLE_CLIENTE_VIEW]
        ROLE_CLIENTE_CREATE: [ROLE_CLIENTE_VIEW, ROLE_CLIENTE_CREATE]
        ROLE_CLIENTE_EDIT: [ROLE_CLIENTE_VIEW, ROLE_CLIENTE_EDIT]
        ROLE_CLIENTE_DELETE: [ROLE_CLIENTE_VIEW, ROLE_CLIENTE_DELETE]
        ROLE_CLIENTE_ALL: [ROLE_CLIENTE_CREATE, ROLE_CLIENTE_EDIT, ROLE_CLIENTE_DELETE, ROLE_CLIENTE_ALL]
